matrix:
  include:
    - language: python
      cache: pip
      python:
        - "3.7"

    - language: node_js
      cache: yarn, pip
      node_js:
        - "10.16.0"
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn global add gulp-cli
        - yarn install
      script:
        - yarn run init
        - yarn run build-prod
        - docker build -t $DOCKER_REPO .

services:
  - docker
env:
  global:
  - DOCKER_REPO=transparent-path/react-ui

deploy:
  provider: script
  script: bash scripts/deploy-aws.sh
  on:
    branch: master
