export const routes = {
  LOGIN: '/login',
  EMAIL_VERIFICATION: '/verify-email/:token',
  REGISTER: '/register',
  RESET_PASSWORD: '/reset-password',
  VERIFICATION: '/verification',
  RESET_PASSWORD_CONFIRM: '/reset-password-confirm',
  APP: '/app',
  USER_MANAGEMENT: '/app/profile/users',
  CURRENT_USERS: '/app/profile/users/current-users',
  USER_GROUPS: '/app/profile/users/groups',
  COMMUNITY: '/app/community',
  RELATIONSHIP: '/app/relationship',
  MANAGEMENT: '/app/management',
};
